### ISSUE TITLE
Issue with latest update

### ISSUE THREAD

**Issue by bossanova808** [angell-co/Spoon#38]
Just did a composer update and this resulted in an error related to Spoon when then trying to load the control panel:
```
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fields.searchable' in 'field list' in /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/db/Command.php:1258
Stack trace:
#0 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/db/Command.php(1258): PDOStatement->execute()
#1 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `fields`...')
#2 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Command->queryOne()
#4 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/db/Query.php(177): yii\db\Query->one(NULL)
#5 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/services/Fields.php(690): craft\db\Query->one()
#6 /var/www/vhosts/c3-dev/vendor/angellco/spoon/src/services/BlockTypes.php(402): craft\services\Fields->getFieldById(23)
#7 /var/www/vhosts/c3-dev/vendor/angellco/spoon/src/services/BlockTypes.php(144): angellco\spoon\services\BlockTypes->_populateBlockTypeFromRecord(Object(angellco\spoon\records\BlockType))
#8 /var/www/vhosts/c3-dev/vendor/angellco/spoon/src/services/Loader.php(176): angellco\spoon\services\BlockTypes->getByContext('global', 'context')
#9 /var/www/vhosts/c3-dev/vendor/angellco/spoon/src/services/Loader.php(144): angellco\spoon\services\Loader->fieldManipulator('global')
#10 /var/www/vhosts/c3-dev/vendor/angellco/spoon/src/Spoon.php(92): angellco\spoon\services\Loader->run()
#11 [internal function]: angellco\spoon\Spoon->angellco\spoon\{closure}(Object(yii\base\Event))
#12 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Object(Closure), Object(yii\base\Event))
#13 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'afterLoadPlugin...', Object(yii\base\Event))
#14 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/services/Plugins.php(260): yii\base\Component->trigger('afterLoadPlugin...')
#15 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/base/ApplicationTrait.php(1186): craft\services\Plugins->loadPlugins()
#16 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/web/Application.php(109): craft\web\Application->_postInit()
#17 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#18 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#19 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/web/Application.php(97): yii\base\Application->__construct(Array)
#20 [internal function]: craft\web\Application->__construct(Array)
#21 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#22 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#23 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#24 /var/www/vhosts/c3-dev/vendor/craftcms/cms/bootstrap/bootstrap.php(252): yii\BaseYii::createObject(Array)
#25 /var/www/vhosts/c3-dev/vendor/craftcms/cms/bootstrap/web.php(42): require('/var/www/vhosts...')
#26 /var/www/vhosts/c3-dev/web/index.php(20): require('/var/www/vhosts...')
#27 {main}

Next yii\db\Exception: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'fields.searchable' in 'field list'
The SQL being executed was: SELECT `fields`.`id`, `fields`.`dateCreated`, `fields`.`dateUpdated`, `fields`.`groupId`, `fields`.`name`, `fields`.`handle`, `fields`.`context`, `fields`.`instructions`, `fields`.`searchable`, `fields`.`translationMethod`, `fields`.`translationKeyFormat`, `fields`.`type`, `fields`.`settings`, `fields`.`uid`
FROM `craft_fields` `fields`
WHERE `fields`.`id`=23
ORDER BY `fields`.`name`, `fields`.`handle`
LIMIT 1 in /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/db/Schema.php:664
Stack trace:
#0 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'SELECT `fields`...')
#1 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/db/Command.php(1148): yii\db\Command->internalExecute('SELECT `fields`...')
#2 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/db/Command.php(413): yii\db\Command->queryInternal('fetch', NULL)
#3 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Command->queryOne()
#4 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/db/Query.php(177): yii\db\Query->one(NULL)
#5 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/services/Fields.php(690): craft\db\Query->one()
#6 /var/www/vhosts/c3-dev/vendor/angellco/spoon/src/services/BlockTypes.php(402): craft\services\Fields->getFieldById(23)
#7 /var/www/vhosts/c3-dev/vendor/angellco/spoon/src/services/BlockTypes.php(144): angellco\spoon\services\BlockTypes->_populateBlockTypeFromRecord(Object(angellco\spoon\records\BlockType))
#8 /var/www/vhosts/c3-dev/vendor/angellco/spoon/src/services/Loader.php(176): angellco\spoon\services\BlockTypes->getByContext('global', 'context')
#9 /var/www/vhosts/c3-dev/vendor/angellco/spoon/src/services/Loader.php(144): angellco\spoon\services\Loader->fieldManipulator('global')
#10 /var/www/vhosts/c3-dev/vendor/angellco/spoon/src/Spoon.php(92): angellco\spoon\services\Loader->run()
#11 [internal function]: angellco\spoon\Spoon->angellco\spoon\{closure}(Object(yii\base\Event))
#12 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Object(Closure), Object(yii\base\Event))
#13 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'afterLoadPlugin...', Object(yii\base\Event))
#14 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/services/Plugins.php(260): yii\base\Component->trigger('afterLoadPlugin...')
#15 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/base/ApplicationTrait.php(1186): craft\services\Plugins->loadPlugins()
#16 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/web/Application.php(109): craft\web\Application->_postInit()
#17 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#18 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#19 /var/www/vhosts/c3-dev/vendor/craftcms/cms/src/web/Application.php(97): yii\base\Application->__construct(Array)
#20 [internal function]: craft\web\Application->__construct(Array)
#21 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#22 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#23 /var/www/vhosts/c3-dev/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#24 /var/www/vhosts/c3-dev/vendor/craftcms/cms/bootstrap/bootstrap.php(252): yii\BaseYii::createObject(Array)
#25 /var/www/vhosts/c3-dev/vendor/craftcms/cms/bootstrap/web.php(42): require('/var/www/vhosts...')
#26 /var/www/vhosts/c3-dev/web/index.php(20): require('/var/www/vhosts...')
#27 {main}
Additional Information:
Array
(
    [0] => 42S22
    [1] => 1054
    [2] => Unknown column 'fields.searchable' in 'field list'
)
```

**Comment by joshangell** [comment]
Thanks Jeremy - I will have a look into it today for you.

**Comment by bossanova808** [comment]
Thanks Josh - no super hurry on my account...jsut thought you might want to know in case more important folks hit it :)

**Comment by joshangell** [comment]
OK I’ve started to dig into this but can’t actually reproduce it ... I think if you disable / uninstall Spoon it may help to see if you still get the errors?

As far as I can tell from the stack trace Craft is trying to load a field layout on a block that has the field handle `searchable` in it, but that field no longer exists.

**Comment by joshangell** [comment]
Hey Jeremy - thanks for the update and no worries - hope you get it sorted!
