### ISSUE TITLE
Spoon error updating to Craft 3.1

### ISSUE THREAD

**Issue by lukebailey** [angell-co/Spoon#43]
Hi

We have isolated the error shown below, upgrading from Craft 3.0.37 to 3.1.0, to be caused by the Spoon plugin:

![image](https://user-images.githubusercontent.com/3185073/51252690-63b26280-1994-11e9-9629-df2202ee3be4.png)

Is this something that could kindly be investigated?

Thanks

Luke

**Comment by lukebailey** [comment]
As a workaround, we can disable Spoon > Apply Craft 3.1 update > Re-enable Spoon

**Comment by joshangell** [comment]
Hey @lukebailey I think I’ve just fixed this ... give it an update and see :)

**Comment by phoob** [comment]
Hello! I had the same issue.. Now I installed 3.2.5, deactivated the plugin, updated Craft to 3.1.1, and reactivated the plugin. Then I got this error.. 

```
yii\base\ErrorException: Trying to get property 'handle' of non-object in /var/www/html/vendor/angellco/spoon/src/services/BlockTypes.php:404
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError(8, 'Trying to get p...', '/var/www/html/v...', 404)
#1 /var/www/html/vendor/angellco/spoon/src/services/BlockTypes.php(404): craft\web\ErrorHandler->handleError(8, 'Trying to get p...', '/var/www/html/v...', 404, Array)
#2 /var/www/html/vendor/angellco/spoon/src/services/BlockTypes.php(145): angellco\spoon\services\BlockTypes->_populateBlockTypeFromRecord(Object(angellco\spoon\records\BlockType))
#3 /var/www/html/vendor/angellco/spoon/src/services/Loader.php(176): angellco\spoon\services\BlockTypes->getByContext('global', 'context')
#4 /var/www/html/vendor/angellco/spoon/src/services/Loader.php(144): angellco\spoon\services\Loader->fieldManipulator('global')
#5 /var/www/html/vendor/angellco/spoon/src/Spoon.php(93): angellco\spoon\services\Loader->run()
#6 [internal function]: angellco\spoon\Spoon->angellco\spoon\{closure}(Object(yii\base\Event))
#7 /var/www/html/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Object(Closure), Object(yii\base\Event))
#8 /var/www/html/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'afterLoadPlugin...', Object(yii\base\Event))
#9 /var/www/html/vendor/craftcms/cms/src/services/Plugins.php(268): yii\base\Component->trigger('afterLoadPlugin...')
#10 /var/www/html/vendor/craftcms/cms/src/services/Plugins.php(772): craft\services\Plugins->loadPlugins()
#11 /var/www/html/vendor/craftcms/cms/src/helpers/Component.php(66): craft\services\Plugins->isPluginEnabled('redactor')
#12 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(546): craft\helpers\Component::createComponent(Array, 'craft\\base\\Fiel...')
#13 /var/www/html/vendor/craftcms/cms/src/services/Fields.php(571): craft\services\Fields->createField(Array)
#14 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1536): craft\services\Fields->getAllFields()
#15 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1073): craft\elements\db\ElementQuery->customFields()
#16 /var/www/html/vendor/yiisoft/yii2/db/QueryBuilder.php(227): craft\elements\db\ElementQuery->prepare(Object(craft\db\mysql\QueryBuilder))
#17 /var/www/html/vendor/yiisoft/yii2/db/Query.php(146): yii\db\QueryBuilder->build(Object(craft\elements\db\UserQuery))
#18 /var/www/html/vendor/yiisoft/yii2/db/Query.php(274): yii\db\Query->createCommand(Object(craft\db\Connection))
#19 /var/www/html/vendor/craftcms/cms/src/db/Query.php(177): yii\db\Query->one(NULL)
#20 /var/www/html/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1215): craft\db\Query->one(NULL)
#21 /var/www/html/vendor/craftcms/cms/src/elements/User.php(367): craft\elements\db\ElementQuery->one()
#22 /var/www/html/vendor/yiisoft/yii2/web/User.php(690): craft\elements\User::findIdentity('914')
#23 /var/www/html/vendor/craftcms/cms/src/web/User.php(474): yii\web\User->renewAuthStatus()
#24 /var/www/html/vendor/yiisoft/yii2/web/User.php(192): craft\web\User->renewAuthStatus()
#25 /var/www/html/modules/elasticsearchmodule/src/ElasticsearchModule.php(140): yii\web\User->getIdentity()
#26 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): modules\elasticsearchmodule\ElasticsearchModule->init()
#27 /var/www/html/vendor/yiisoft/yii2/base/Module.php(158): yii\base\BaseObject->__construct(Array)
#28 /var/www/html/modules/elasticsearchmodule/src/ElasticsearchModule.php(104): yii\base\Module->__construct('elasticsearch-m...', Object(craft\web\Application), Array)
#29 [internal function]: modules\elasticsearchmodule\ElasticsearchModule->__construct('elasticsearch-m...', Object(craft\web\Application), Array)
#30 /var/www/html/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#31 /var/www/html/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('modules\\elastic...', Array, Array)
#32 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('modules\\elastic...', Array, Array)
#33 /var/www/html/vendor/yiisoft/yii2/base/Module.php(427): yii\BaseYii::createObject(Array, Array)
#34 /var/www/html/vendor/yiisoft/yii2/base/Application.php(315): yii\base\Module->getModule('elasticsearch-m...')
#35 /var/www/html/vendor/craftcms/cms/src/web/Application.php(128): yii\base\Application->bootstrap()
#36 /var/www/html/vendor/yiisoft/yii2/base/Application.php(273): craft\web\Application->bootstrap()
#37 /var/www/html/vendor/craftcms/cms/src/web/Application.php(110): yii\base\Application->init()
#38 /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#39 /var/www/html/vendor/yiisoft/yii2/base/Application.php(206): yii\base\BaseObject->__construct(Array)
#40 /var/www/html/vendor/craftcms/cms/src/web/Application.php(100): yii\base\Application->__construct(Array)
#41 [internal function]: craft\web\Application->__construct(Array)
#42 /var/www/html/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs(Array)
#43 /var/www/html/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('craft\\web\\Appli...', Array, Array)
#44 /var/www/html/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('craft\\web\\Appli...', Array, Array)
#45 /var/www/html/vendor/craftcms/cms/bootstrap/bootstrap.php(255): yii\BaseYii::createObject(Array)
#46 /var/www/html/vendor/craftcms/cms/bootstrap/web.php(42): require('/var/www/html/v...')
#47 /var/www/html/web/index.php(35): require('/var/www/html/v...')
#48 {main}
```

**Comment by joshangell** [comment]
Hi Peter, thanks for this.

I'm out of the office today but I should be able to push a fix for this
tomorrow.

**Comment by joshangell** [comment]
Hi @phoob you can give it another whirl now, just pushed a release that should fix this ...

**Comment by phoob** [comment]
> Hi @phoob you can give it another whirl now, just pushed a release that should fix this ...

Hi @joshangell ! I still had this problem. Made it vanish by refreshing field cache before using fields->getFieldsById(...). See pull request!

**Comment by joshangell** [comment]
@phoob ah brilliant, thank you!
