### ISSUE TITLE
Issue with Super Table support, BlockTypes SuperTableService::getBlockTypeById()

### ISSUE THREAD

**Issue by ccchapman** [angell-co/Spoon#44]
I am having troubles activating Spoon on a Craft CMS installation with [verbb/super-table](https://github.com/verbb/super-table).

Steps to reproduce:

1. Existing project has Craft CMS and Super Table (versions shown below)
2. `composer require angellco/spoon`
3. Load admin UI
4. Receive PHP notice shown below

```
yii\base\ErrorException: A non well formed numeric value encountered in /home/vagrant/craftcms/vendor/verbb/super-table/src/services/SuperTableService.php:119
Stack trace:
#0 /home/vagrant/craftcms/vendor/angellco/spoon/src/services/BlockTypes.php(425): verbb\supertable\services\SuperTableService->getBlockTypeById()
#1 /home/vagrant/craftcms/vendor/angellco/spoon/src/services/BlockTypes.php(145): angellco\spoon\services\BlockTypes->_populateBlockTypeFromRecord()
#2 /home/vagrant/craftcms/vendor/angellco/spoon/src/services/Loader.php(176): angellco\spoon\services\BlockTypes->getByContext()
#3 /home/vagrant/craftcms/vendor/angellco/spoon/src/services/Loader.php(144): angellco\spoon\services\Loader->fieldManipulator()
#4 /home/vagrant/craftcms/vendor/angellco/spoon/src/Spoon.php(93): angellco\spoon\services\Loader->run()
#5 /home/vagrant/craftcms/vendor/yiisoft/yii2/base/Event.php(310): angellco\spoon\Spoon->angellco\spoon\{closure}()
#6 /home/vagrant/craftcms/vendor/yiisoft/yii2/base/Event.php(310): ::call_user_func:{/home/vagrant/craftcms/vendor/yiisoft/yii2/base/Event.php:310}()
#7 /home/vagrant/craftcms/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger()
#8 /home/vagrant/craftcms/vendor/craftcms/cms/src/services/Plugins.php(268): craft\services\Plugins->trigger()
#9 /home/vagrant/craftcms/vendor/craftcms/cms/src/base/ApplicationTrait.php(1187): craft\services\Plugins->loadPlugins()
#10 /home/vagrant/craftcms/vendor/craftcms/cms/src/web/Application.php(112): craft\web\Application->_postInit()
#11 /home/vagrant/craftcms/vendor/yiisoft/yii2/base/BaseObject.php(109): craft\web\Application->init()
#12 /home/vagrant/craftcms/vendor/yiisoft/yii2/base/Application.php(206): craft\web\Application->__construct()
#13 /home/vagrant/craftcms/vendor/craftcms/cms/src/web/Application.php(100): craft\web\Application->__construct()
#14 /home/vagrant/craftcms/vendor/yiisoft/yii2/di/Container.php(383): craft\web\Application->__construct()
#15 /home/vagrant/craftcms/vendor/yiisoft/yii2/di/Container.php(383): ReflectionClass->newInstanceArgs()
#16 /home/vagrant/craftcms/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build()
#17 /home/vagrant/craftcms/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get()
#18 /home/vagrant/craftcms/vendor/craftcms/cms/bootstrap/bootstrap.php(255): yii\BaseYii::createObject()
#19 /home/vagrant/craftcms/vendor/craftcms/cms/bootstrap/web.php(42): ::unknown()
#20 /home/vagrant/craftcms/web/index.php(20): ::unknown()
#21 {main}
```

Craft CMS Version:  3.1.2.2
Super Table Version: 2.1.4.2
PHP Version: 7.2.11

cc @engram-design @joshangell

**Comment by engram-design** [comment]
@ccchapman I've not dived into this specific issue, but [2.1.5](https://github.com/verbb/super-table/releases/tag/2.1.5), was just released to hopefully put any content table issues to rest. It's worth updating to that and running the new `/actions/super-table/plugin/check-content-tables` action endpoint to check Super Table content tables.

**Comment by ccchapman** [comment]
@engram-design After updating to Super Table 2.1.5 and running the new action endpoint, I still receive the PHP notice.

**Comment by joshangell** [comment]
Hi both, this is definitely a Spoon issue, I should be able to fix it today.

**Comment by joshangell** [comment]
Better late than never ... sorry for the delay @ccchapman!

**Comment by ccchapman** [comment]
@joshangell Confirming it works on my end! Thank you for the update.

**Comment by joshangell** [comment]
Awesome!
